apiVersion: v1 # api version of kubernetes
kind: Pod # what of object to deploy
metadata: # data for object
  name: react-pod
  labels:
    zone: prod
    version: v1
spec: # what is in the resource
  containers: 
    - name: react-container # name of the container
      image: bledarsulmata/react-scrapper-image # path to image
      imagePullPolicy: IfNotPresent
      ports: # where will we expose the container
      - containerPort: 80
