FROM adoptopenjdk/openjdk8

MAINTAINER Bledar Sulmataj <bledar.sulmataj8@gmail.com>

COPY target/Start-0.0.1-SNAPSHOT.jar Start-0.0.1-SNAPSHOT.jar

CMD ["java", "-jar",  "/Start-0.0.1-SNAPSHOT.jar"]

EXPOSE 8090
