apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: database
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: DB	
    spec:
      containers:
      - name: database-pod
        image: bledarsulmata/scrapper-database
        ports:
        - containerPort: 3306
