apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: FE	
    spec:
      containers:
      - name: react-pod
        image: bledarsulmata/react-scrapper-image
        ports:
        - containerPort: 80
