apiVersion: v1
kind: Service
metadata: 
  name: backend-service
  labels:
    app: spring-pod
spec:
  type: NodePort
  ports:
    - port: 8090
      nodePort: 30090 
      protocol: TCP
  selector:
     app: BE
