apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
  labels:
    app: react-pod
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30002 
      protocol: TCP
  selector:
     app: FE
